backend:
  name: github
  repo: moisesibanez17/JoyeriaJosefina
  branch: main
  base_url: https://decap-oauth-mu.vercel.app
  auth_endpoint: api/auth

media_folder: "src/img/catalogo"
public_folder: "/JoyeriaJosefina/src/img/catalogo"
logo_url: "../img/logo.jpg"

collections:
  - name: "catalogo_global"
    label: "Catalogo de Joyas"
    folder: "src/data/joyas"
    format: json
    extension: json
    create: true
    slug: "{{nombre}}-{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}"
    identifier_field: "nombre"
    summary: '{{nombre}} - {{precio}} - {{coleccion}}'
    fields:
      - {label: "Nombre de la Joya", name: "nombre", widget: "string"}
      - {label: "Coleccion", name: "coleccion", widget: "select", options: ["Coleccion Oro", "Plata y Platino", "Gemas Clasicas", "Argollas de Matrimonio"]}
      - {label: "Etiqueta Destacada (ej. Pieza Unica)", name: "estado", widget: "string", required: false}
      - {label: "Precio al publico (solo numero, ej. 45800)", name: "precio", widget: "number"}
      - {label: "Fotografia", name: "imagen", widget: "image"}
      - {label: "Corte / Estilo", name: "corte", widget: "string"}
      - {label: "Material / Quilates", name: "material", widget: "string"}
      - {label: "Consejo Gemologico Breve", name: "nota", widget: "text"}
