backend:
  name: github
  repo: moisesibanez17/JoyeriaJosefina
  branch: main
  base_url: https://decap-oauth-mu.vercel.app
  auth_endpoint: api/auth

media_folder: "src/img/catalogo" # Carpeta donde el CMS guarda las fotos nuevas
public_folder: "../../img/catalogo" # Ruta que la web lee para mostrar la foto
logo_url: "../img/logo.jpg" # Logo de la marca

collections:
  - name: "catalogo_global"
    label: "Catálogo de Joyas"
    folder: "src/data/joyas"
    format: json
    extension: json
    create: true
    slug: "{{fields.id}}"
    identifier_field: "nombre"
    summary: '{{nombre}} — {{precio}} — {{coleccion}}'
    fields:
      - {label: "ID de la Página (ej. anillo-solitario)", name: "id", widget: "string"}
      - {label: "Nombre de la Joya", name: "nombre", widget: "string"}
      - {label: "Colección", name: "coleccion", widget: "select", options: ["Colección Oro", "Plata y Platino", "Gemas Clásicas", "Argollas de Matrimonio"]}
      - {label: "Etiqueta Destacada (ej. Pieza Única, N/A para vacío)", name: "estado", widget: "string", required: false}
      - {label: "Precio al público", name: "precio", widget: "string"}
      - {label: "Fotografía", name: "imagen", widget: "image"}
      - {label: "Corte / Estilo", name: "corte", widget: "string"}
      - {label: "Material / Quilates", name: "material", widget: "string"}
      - {label: "Consejo Gemológico Breve", name: "nota", widget: "text"}
